### ISSUE TITLE
An error when emacs startup

### ISSUE THREAD

**Issue by KiteAB** [DogLooksGood/storybook-theme#1]
`set-face-attribute: Invalid face box: :line-width, (-1 . -2), :color, "#edccb7", :style, nil`
My theme load code:
```emacs-lisp
(require 'lazycat-theme)
;; (lazycat-theme-load-dark)
(require 'joker-theme)
(require 'storybook-theme)
(require 'printed-theme)
(load-theme 'storybook t)
```

**Comment by DogLooksGood** [comment]
I think the negative line-width is a new feature in Emacs28.

**Comment by KiteAB** [comment]
oops

**Comment by DogLooksGood** [comment]
I think you are on Arch Linux, emacs28 is stable, I've been using it for months. It also have native-comp features than can speed up some functionalities.

So I recommend an update here.
