### ISSUE TITLE
There's a row position offset when selecting the current row

### ISSUE THREAD

**Issue by KiteAB** [DogLooksGood/storybook-theme#2]
![eg](https://user-images.githubusercontent.com/45714280/104798787-6276d300-5804-11eb-8cbf-074fc855f9f2.gif)

**Comment by KiteAB** [comment]
Ummm.... There's the example video: https://cowtransfer.com/s/4720c09ca56942

**Comment by DogLooksGood** [comment]
You need
```
 (setq x-underline-at-descent-line t)
```

**Comment by KiteAB** [comment]
> You need
> 
> ```
>  (setq x-underline-at-descent-line t)
> ```

我应该是没描述清楚？
就是每移动一行 新的当前行的行位置会向下偏移一点

**Comment by KiteAB** [comment]
另外meow光标的样式也可以改改

**Comment by DogLooksGood** [comment]
maybe this?
```
(setq underline-minimum-offset 0)
```
I also have this one
```
(setq  overline-margin 0)
```

**Comment by DogLooksGood** [comment]
> 另外meow光标的样式也可以改改

any suggestion is appreciated.

**Comment by KiteAB** [comment]
> (setq underline-minimum-offset 0)

This one. Thx
> any suggestion is appreciated.

I may raise PR later
